# Заполни конфигурацию для тестового проекта, укажи в нем необходимые ресурсы, например:

#[[http]]
#service_name = "example_service_01"
#swagger = "http://example_service_01/example-api/openapi.json"

#[[http]]
#service_name = "example_service_02"
#swagger = "http://example_service_02/example-api/openapi.json"
